const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('linsoftBrowser', {
  isDesktopApp: true,
  appName: 'Linsoft Browser',
  windowControl: (action) => ipcRenderer.send('window-control', action),
  onWindowCloseRequest: (callback) => ipcRenderer.on('window-close-request', () => callback()),
  confirmWindowClose: () => ipcRenderer.send('confirm-window-close'),
  onDownload: (callback) => ipcRenderer.on('download-update', (_event, data) => callback(data)),
  listDownloads: () => ipcRenderer.invoke('download-list'),
  removeDownload: (id) => ipcRenderer.invoke('download-remove', id),
  clearDownloads: () => ipcRenderer.invoke('download-clear'),
  openDownloads: () => ipcRenderer.send('open-downloads'),
  selectDownloadFolder: () => ipcRenderer.invoke('select-download-folder'),
  openDownloadFile: (filePath) => ipcRenderer.send('open-download-file', filePath),
  showDownloadFile: (filePath) => ipcRenderer.send('show-download-file', filePath),
  cancelDownload: (fileName) => ipcRenderer.send('cancel-download', fileName),
  pauseDownload: (id) => ipcRenderer.send('pause-download', id),
  resumeDownload: (id) => ipcRenderer.send('resume-download', id),
  setBrowserPreferences: (preferences) => ipcRenderer.send('set-browser-preferences', preferences),
  getVersion: () => ipcRenderer.invoke('app-version'),
  checkForUpdates: () => ipcRenderer.invoke('update-check'),
  downloadUpdate: () => ipcRenderer.invoke('update-download'),
  installUpdate: () => ipcRenderer.send('update-install'),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
    savePagePdf: (webContentsId) => ipcRenderer.invoke('save-page-pdf', webContentsId),
    capturePage: (webContentsId) => ipcRenderer.invoke('capture-page', webContentsId),
    capturePageToClipboard: (webContentsId) => ipcRenderer.invoke('capture-page-to-clipboard', webContentsId),
  listPasswords: () => ipcRenderer.invoke('password-list'),
  getPassword: (id) => ipcRenderer.invoke('password-get', id),
  savePassword: (entry) => ipcRenderer.invoke('password-save', entry),
  deletePassword: (id) => ipcRenderer.invoke('password-delete', id),
  getAdblockStats: () => ipcRenderer.invoke('adblock-stats'),
  toggleAdblockSite: (hostname) => ipcRenderer.invoke('adblock-toggle-site', hostname),
  updateAdblockList: () => ipcRenderer.invoke('adblock-update-list'),
  onExternalUrl: (callback) => ipcRenderer.on('open-external-url', (_event, url) => callback(url)),
    onOpenAppCenter: (callback) => ipcRenderer.on('open-app-center', () => callback()),
  onInstallExternalApp: (callback) => ipcRenderer.on('install-external-app', (_event, data) => callback(data)),
  openBrowserWindow: (url) => ipcRenderer.send('open-browser-window', url),
  openDetachedWindow: (url) => ipcRenderer.send('open-detached-window', url),
  onLinkInTab: (callback) => ipcRenderer.on('open-link-in-tab', (_event, url) => callback(url)),
  onBrowserShortcut: (callback) => ipcRenderer.on('browser-shortcut', (_event, data) => callback(data)),
  onWebviewContextMenu: (callback) => ipcRenderer.on('webview-context-menu', (_event, data) => callback(data)),
  installWebApp: (url, title) => ipcRenderer.invoke('install-web-app', { url, title }),
    uninstallWebApp: (url, title) => ipcRenderer.invoke('uninstall-web-app', { url, title }),
    onUninstallExternalApp: (callback) => ipcRenderer.on('uninstall-external-app', (_event, data) => callback(data)),
  selectOpenVpnProfile: () => ipcRenderer.invoke('openvpn-select-profile'),
  connectOpenVpn: (profile) => ipcRenderer.send('openvpn-connect', profile),
  disconnectOpenVpn: () => ipcRenderer.send('openvpn-disconnect'),
  onOpenVpnStatus: (callback) => ipcRenderer.on('openvpn-status', (_event, status) => callback(status)),
  getOpenVpnPath: () => ipcRenderer.invoke('openvpn-path')
});
